package bbstore

import (
	"fmt"
	"sort"
	"time"

	"github.com/bborn/bb-tui/internal/db"
)

// DemoStore serves an invented workspace. It exists so the screenshots in this
// repository can be regenerated by anyone, from data that belongs to nobody,
// without a bb server running.
type DemoStore struct {
	tasks []*db.Task
	logs  map[int64][]*db.TaskLog
}

func ago(d time.Duration) db.LocalTime {
	return db.LocalTime{Time: time.Now().Add(-d)}
}

func demoTask(id int64, title, project, status, branch string, pinned bool, age time.Duration) *db.Task {
	return &db.Task{
		ID:           id,
		Title:        title,
		Project:      project,
		Status:       status,
		Type:         "code",
		Executor:     "claude-code",
		BranchName:   branch,
		WorktreePath: "/work/" + branch,
		Pinned:       pinned,
		CreatedAt:    ago(age + time.Hour),
		UpdatedAt:    ago(age),
	}
}

// NewDemoStore builds a workspace that looks like a working day: something
// running, a couple of things waiting on an answer, and a pile of finished work.
func NewDemoStore() *DemoStore {
	tasks := []*db.Task{
		demoTask(41, "Add rate limiting to the public API", "gateway", db.StatusProcessing, "feat/rate-limit", false, 4*time.Minute),
		demoTask(38, "Port the billing webhooks to the new queue", "payments", db.StatusProcessing, "feat/webhook-queue", true, 21*time.Minute),
		demoTask(36, "Investigate flaky checkout test", "storefront", db.StatusBlocked, "fix/flaky-checkout", false, 2*time.Hour),
		demoTask(33, "Upgrade Postgres driver to 5.x", "gateway", db.StatusBlocked, "chore/pg-5", false, 5*time.Hour),
		demoTask(30, "Cache product images at the edge", "storefront", db.StatusBlocked, "perf/edge-cache", false, 26*time.Hour),
		demoTask(28, "Document the deploy runbook", "infra", db.StatusQueued, "docs/runbook", false, 9*time.Minute),
		demoTask(44, "Add a status page for the API", "gateway", db.StatusBacklog, "feat/status-page", false, 2*time.Minute),
		demoTask(43, "Sweep unused feature flags", "infra", db.StatusBacklog, "chore/flag-sweep", false, 35*time.Minute),
		demoTask(24, "Split the monolith's auth module", "gateway", db.StatusDone, "refactor/auth-split", true, 3*time.Hour),
		demoTask(22, "Add dark mode to the dashboard", "storefront", db.StatusDone, "feat/dark-mode", false, 7*time.Hour),
		demoTask(19, "Retry failed payouts with backoff", "payments", db.StatusDone, "fix/payout-retry", false, 20*time.Hour),
		demoTask(17, "Trim the Docker image to 400MB", "infra", db.StatusDone, "perf/slim-image", false, 2*24*time.Hour),
		demoTask(12, "Move secrets out of the repo", "infra", db.StatusDone, "chore/secrets", false, 4*24*time.Hour),
	}

	logs := map[int64][]*db.TaskLog{
		38: {
			{ID: 1, TaskID: 38, LineType: "user", Content: "Move the billing webhooks onto the new queue. Keep the old endpoint alive behind a flag until we've drained it.", CreatedAt: ago(24 * time.Minute)},
			{ID: 2, TaskID: 38, LineType: "system", Content: "Thought for 6s", CreatedAt: ago(24 * time.Minute)},
			{ID: 3, TaskID: 38, LineType: "text", Content: "Starting with the consumer, since the endpoint can't be retired until something else is reading the queue.\n\nThe plan:\n\n1. **Consumer first** — read from `billing.webhooks`, ack on success\n2. **Dual-write** the endpoint behind `WEBHOOK_QUEUE_ENABLED`\n3. Drain, then delete the endpoint\n\n```go\nfunc (c *Consumer) Handle(ctx context.Context, m Message) error {\n\treturn c.billing.Apply(ctx, m.Event)\n}\n```", CreatedAt: ago(23 * time.Minute)},
			{ID: 4, TaskID: 38, LineType: "tool", Content: "$ go test ./internal/billing/...", CreatedAt: ago(22 * time.Minute)},
			{ID: 5, TaskID: 38, LineType: "tool", Content: "edit internal/billing/consumer.go", CreatedAt: ago(22 * time.Minute)},
			{ID: 6, TaskID: 38, LineType: "text", Content: "Consumer is in and the tests pass. Dual-writing next — the flag defaults off, so nothing changes until it's turned on.", CreatedAt: ago(21 * time.Minute)},
		},
		36: {
			{ID: 1, TaskID: 36, LineType: "user", Content: "The checkout test fails about one run in five on CI but never locally. Find out why.", CreatedAt: ago(3 * time.Hour)},
			{ID: 2, TaskID: 36, LineType: "tool", Content: "$ go test ./internal/checkout -run TestCheckout -count=50", CreatedAt: ago(3 * time.Hour)},
			{ID: 3, TaskID: 36, LineType: "text", Content: "Reproduced at `-count=50`: two failures, both in `TestCheckoutAppliesDiscount`. The fixture seeds a discount that expires *now*, so whether it is still valid depends on how long the preceding tests took.", CreatedAt: ago(2 * time.Hour)},
			{ID: 4, TaskID: 36, LineType: "question", Content: "Pin the fixture clock, or give the discount a fixed future expiry? — waiting for you", CreatedAt: ago(2 * time.Hour)},
		},
	}

	return &DemoStore{tasks: tasks, logs: logs}
}

func (s *DemoStore) ListTasks(opts db.ListTasksOptions) ([]*db.Task, error) {
	out := make([]*db.Task, 0, len(s.tasks))
	for _, task := range s.tasks {
		if !matchesStatus(task, opts) {
			continue
		}
		if opts.Project != "" && task.Project != opts.Project {
			continue
		}
		out = append(out, task)
	}
	if !opts.OrderByRecency {
		sort.SliceStable(out, func(i, j int) bool {
			if out[i].Pinned != out[j].Pinned {
				return out[i].Pinned
			}
			return out[i].UpdatedAt.Time.After(out[j].UpdatedAt.Time)
		})
	}
	if opts.Limit > 0 && len(out) > opts.Limit {
		out = out[:opts.Limit]
	}
	return out, nil
}

func (s *DemoStore) GetTask(id int64) (*db.Task, error) {
	for _, task := range s.tasks {
		if task.ID == id {
			clone := *task
			return &clone, nil
		}
	}
	return nil, fmt.Errorf("task #%d not found", id)
}

func (s *DemoStore) SearchTasks(query string, limit int) ([]*db.Task, error) {
	return s.ListTasks(db.ListTasksOptions{Limit: limit})
}

func (s *DemoStore) CountTasksByStatus(status string) (int, error) {
	count := 0
	for _, task := range s.tasks {
		if status == db.StatusQueued && db.IsInProgress(task.Status) {
			count++
			continue
		}
		if task.Status == status {
			count++
		}
	}
	return count, nil
}

func (s *DemoStore) CountTasksByProject(project string) (int, error) {
	count := 0
	for _, task := range s.tasks {
		if task.Project == project {
			count++
		}
	}
	return count, nil
}

func (s *DemoStore) GetTaskLogs(taskID int64, limit int) ([]*db.TaskLog, error) {
	return s.logs[taskID], nil
}

func (s *DemoStore) GetTaskLogCount(taskID int64) (int, error) {
	return len(s.logs[taskID]), nil
}

func (s *DemoStore) GetLatestLogPerTask(taskIDs []int64) (map[int64]*db.TaskLog, error) {
	out := map[int64]*db.TaskLog{}
	for _, id := range taskIDs {
		if entries := s.logs[id]; len(entries) > 0 {
			out[id] = entries[len(entries)-1]
		}
	}
	return out, nil
}

func (s *DemoStore) ListProjects() ([]*db.Project, error) {
	return []*db.Project{
		{ID: 1, Name: "gateway"},
		{ID: 2, Name: "payments"},
		{ID: 3, Name: "storefront"},
		{ID: 4, Name: "infra"},
	}, nil
}

func (s *DemoStore) MarkOpened(taskID int64) error { return nil }

// Context is the execution the composer shows for a demo thread.
func (s *DemoStore) Context(taskID int64) ComposerContext {
	task, err := s.GetTask(taskID)
	if err != nil {
		return ComposerContext{}
	}
	return ComposerContext{
		Project:     task.Project,
		Environment: task.BranchName,
		Provider:    task.Executor,
		Model:       "Sonnet 5",
		Reasoning:   "high",
		Permission:  "accept-edits",
	}
}

// Activity reports a running thread as working, for the indicator.
func (s *DemoStore) Activity(taskID int64) (bool, string) {
	task, err := s.GetTask(taskID)
	if err != nil || task.Status != db.StatusProcessing {
		return false, ""
	}
	return true, "18s"
}
